SELECT e.F_NAME, e.L_NAME, jh.START_DATE, j.JOB_TITLE FROM EMPLOYEES e 
JOIN JOB_HISTORY jh ON e.EMP_ID = jh.EMPL_ID 
JOIN JOBS j ON j.JOB_IDENT = jh.JOBS_ID 
WHERE e.DEP_ID = 5;


SELECT e.EMP_ID, e.L_NAME, e.DEP_ID, d.DEP_NAME FROM EMPLOYEES e
LEFT JOIN DEPARTMENTS d ON e.DEP_ID = d.DEPT_ID_DEP 
AND YEAR(e.B_DATE) < 1980;


SELECT E.F_NAME, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME
FROM EMPLOYEES AS E
LEFT OUTER JOIN DEPARTMENTS AS D
ON E.DEP_ID=D.DEPT_ID_DEP AND E.SEX = 'M'

UNION

SELECT E.F_NAME, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME
from EMPLOYEES AS E
RIGHT OUTER JOIN DEPARTMENTS AS D
ON E.DEP_ID=D.DEPT_ID_DEP AND E.SEX = 'M';